import type {
  AssessmentBlueprint,
  AssessmentItemRevision,
  InteractionTemplateRevision,
  JsonObject,
  PluginPackage,
  SchoolAssessmentState,
  TaxonomyNode,
  TaxonomyScheme,
  TestFormRevision,
} from './types';

const createdAt = '2026-08-20T08:00:00.000Z';

const taxonomySchemes: TaxonomyScheme[] = [
  {
    code: 'KNOWLEDGE',
    description: '按课程维护的知识体系，可存在多棵树并支持跨课程引用。',
    id: 'scheme-knowledge',
    name: '课程知识体系',
    scope: 'knowledge',
    status: 'active',
    structure: 'tree',
    version: 3,
  },
  {
    code: 'ABILITY',
    description: '跨学院共享的能力指标与课程目标。',
    id: 'scheme-ability',
    name: '能力指标',
    scope: 'ability',
    status: 'active',
    structure: 'graph',
    version: 2,
  },
  {
    code: 'GRADUATE',
    description: '培养方案中的毕业要求和认证指标。',
    id: 'scheme-graduate',
    name: '毕业要求',
    scope: 'graduate-outcome',
    status: 'active',
    structure: 'graph',
    version: 4,
  },
  {
    code: 'SCENARIO',
    description: '工程、临床、实验和语言等应用场景。',
    id: 'scheme-scenario',
    name: '应用场景',
    scope: 'application',
    status: 'active',
    structure: 'facet',
    version: 1,
  },
];

const taxonomyNodes: TaxonomyNode[] = [
  {
    aliases: ['微积分'],
    code: 'MATH-CALC',
    courseIds: ['course-calculus'],
    description: '高等数学微积分知识域',
    id: 'node-calculus',
    name: '微积分',
    parentId: null,
    schemeId: 'scheme-knowledge',
  },
  {
    aliases: ['定积分'],
    code: 'MATH-INT',
    courseIds: ['course-calculus'],
    description: '定积分概念、计算与应用',
    id: 'node-integral',
    name: '定积分',
    parentId: 'node-calculus',
    schemeId: 'scheme-knowledge',
  },
  {
    aliases: ['数据结构'],
    code: 'CS-DS',
    courseIds: ['course-programming'],
    description: '程序设计中的基本数据结构',
    id: 'node-data-structure',
    name: '数据结构',
    parentId: null,
    schemeId: 'scheme-knowledge',
  },
  {
    aliases: ['材料力学'],
    code: 'ME-STRESS',
    courseIds: ['course-mechanics'],
    description: '应力、应变与强度计算',
    id: 'node-stress',
    name: '应力与强度',
    parentId: null,
    schemeId: 'scheme-knowledge',
  },
  {
    aliases: ['影像诊断'],
    code: 'MED-IMG',
    courseIds: ['course-diagnostics'],
    description: '医学影像判读与标注',
    id: 'node-imaging',
    name: '影像诊断',
    parentId: null,
    schemeId: 'scheme-knowledge',
  },
  {
    aliases: ['建模'],
    code: 'ABILITY-MODEL',
    courseIds: [],
    description: '把实际问题转化为可计算模型',
    id: 'node-modeling',
    name: '数学建模能力',
    parentId: null,
    schemeId: 'scheme-ability',
  },
  {
    aliases: ['工程分析'],
    code: 'ABILITY-ENG',
    courseIds: [],
    description: '使用工程原理分析复杂问题',
    id: 'node-engineering-analysis',
    name: '工程分析能力',
    parentId: null,
    schemeId: 'scheme-ability',
  },
  {
    aliases: ['临床推理'],
    code: 'ABILITY-CLINICAL',
    courseIds: [],
    description: '依据证据形成临床判断',
    id: 'node-clinical-reasoning',
    name: '临床推理能力',
    parentId: null,
    schemeId: 'scheme-ability',
  },
  {
    aliases: ['毕业要求 1'],
    code: 'GR-01',
    courseIds: [],
    description: '能够应用数学、自然科学和工程基础知识。',
    id: 'node-graduate-1',
    name: '工程知识',
    parentId: null,
    schemeId: 'scheme-graduate',
  },
  {
    aliases: [],
    code: 'SC-ENG',
    courseIds: [],
    description: '工程设计与分析场景',
    id: 'node-scenario-engineering',
    name: '工程场景',
    parentId: null,
    schemeId: 'scheme-scenario',
  },
  {
    aliases: [],
    code: 'SC-MED',
    courseIds: [],
    description: '临床与医学实践场景',
    id: 'node-scenario-medical',
    name: '临床场景',
    parentId: null,
    schemeId: 'scheme-scenario',
  },
];

const interactionTemplates: InteractionTemplateRevision[] = [
  {
    accessibilityNotes: '所有字段均提供标签，单位选择支持键盘操作。',
    checksum: 'template-material-v3',
    controls: [
      {
        config: { max: 1000, min: 0, precision: 2, unit: 'MPa' },
        id: 'ctrl-stress',
        label: '计算应力',
        required: true,
        scoreWeight: 0.5,
        type: 'number',
        width: 2,
      },
      {
        config: { options: ['安全', '临界', '失效'] },
        id: 'ctrl-judgement',
        label: '强度判断',
        required: true,
        scoreWeight: 0.2,
        type: 'single-choice',
        width: 2,
      },
      {
        config: { maxLength: 500, rows: 4 },
        id: 'ctrl-reason',
        label: '说明判断依据',
        required: true,
        scoreWeight: 0.3,
        type: 'textarea',
        width: 4,
      },
    ],
    createdAt,
    createdBy: 'teacher-mechanics',
    description: '数值计算、状态判断和分析说明组成的工程复合交互。',
    familyId: 'template-material',
    id: 'template-material@3',
    name: '材料强度复合计算',
    paperFallback: {
      answerLines: 8,
      mode: 'equivalent',
      note: '纸面保留计算框、判断选项和说明区。',
    },
    revision: 3,
    scoreRules: [
      {
        config: { expected: 250, tolerance: 2 },
        controlId: 'ctrl-stress',
        id: 'rule-stress',
        type: 'range',
        weight: 0.5,
      },
      {
        config: { expected: '安全' },
        controlId: 'ctrl-judgement',
        id: 'rule-judgement',
        type: 'exact',
        weight: 0.2,
      },
      {
        config: { rubric: '分析依据量规 v2' },
        controlId: 'ctrl-reason',
        id: 'rule-reason',
        type: 'human',
        weight: 0.3,
      },
    ],
    status: 'enabled',
  },
  {
    accessibilityNotes: '量规选项同时提供文本描述。',
    checksum: 'template-clinical-v2',
    controls: [
      {
        config: { options: ['正常', '轻度异常', '明显异常', '危急'] },
        id: 'ctrl-severity',
        label: '病情等级',
        required: true,
        scoreWeight: 0.3,
        type: 'rating',
        width: 4,
      },
      {
        config: { maxLength: 800, rows: 6 },
        id: 'ctrl-evidence',
        label: '诊断依据',
        required: true,
        scoreWeight: 0.7,
        type: 'textarea',
        width: 4,
      },
    ],
    createdAt,
    createdBy: 'teacher-medical',
    description: '临床考站中由考生判断、考官记录证据的交互。',
    familyId: 'template-clinical',
    id: 'template-clinical@2',
    name: '临床判断与证据',
    paperFallback: {
      answerLines: 10,
      mode: 'examiner-recorded',
      note: '实践考试由考官记录，纸面仅生成量规。',
    },
    revision: 2,
    scoreRules: [
      {
        config: { rubric: '临床推理四级量规' },
        controlId: 'ctrl-evidence',
        id: 'rule-clinical',
        type: 'rubric',
        weight: 1,
      },
    ],
    status: 'enabled',
  },
];

const pluginPackages: PluginPackage[] = [
  {
    capabilities: {
      accessibility: true,
      authoring: true,
      automaticScoring: true,
      online: true,
      practical: false,
      print: true,
    },
    description: '单选、多选和组合选项，支持部分得分。',
    id: 'core.choice',
    name: '选择交互',
    packageKind: 'built-in',
    sampleItemId: 'item-calculus-choice@2',
    sandbox: 'none',
    status: 'enabled',
    testSummary: { failed: 0, lastRunAt: createdAt, passed: 18 },
    version: '2.1.0',
  },
  {
    capabilities: {
      accessibility: true,
      authoring: true,
      automaticScoring: true,
      online: true,
      practical: false,
      print: true,
    },
    description: '多空文本输入、同义答案和逐空计分。',
    id: 'core.fill',
    name: '填空交互',
    packageKind: 'built-in',
    sandbox: 'none',
    status: 'enabled',
    testSummary: { failed: 0, lastRunAt: createdAt, passed: 14 },
    version: '2.0.0',
  },
  {
    capabilities: {
      accessibility: true,
      authoring: true,
      automaticScoring: true,
      online: true,
      practical: true,
      print: true,
    },
    description: '数值、单位、精度和容差评分。',
    id: 'core.numeric',
    name: '数值与单位',
    packageKind: 'built-in',
    sampleItemId: 'item-integral-numeric@1',
    sandbox: 'none',
    status: 'enabled',
    testSummary: { failed: 0, lastRunAt: createdAt, passed: 21 },
    version: '2.2.0',
  },
  {
    capabilities: {
      accessibility: true,
      authoring: true,
      automaticScoring: false,
      online: true,
      practical: true,
      print: true,
    },
    description: '长文本、公式和人工量规评分。',
    id: 'core.essay',
    name: '论述交互',
    packageKind: 'built-in',
    sandbox: 'none',
    status: 'enabled',
    testSummary: { failed: 0, lastRunAt: createdAt, passed: 11 },
    version: '2.0.0',
  },
  {
    capabilities: {
      accessibility: true,
      authoring: true,
      automaticScoring: false,
      online: true,
      practical: true,
      print: false,
    },
    description: '作品文件、格式限制和证据链。',
    id: 'core.file',
    name: '文件作品',
    packageKind: 'built-in',
    sandbox: 'none',
    status: 'enabled',
    testSummary: { failed: 0, lastRunAt: createdAt, passed: 9 },
    version: '2.0.0',
  },
  {
    capabilities: {
      accessibility: true,
      authoring: true,
      automaticScoring: false,
      online: true,
      practical: true,
      print: true,
    },
    description: '现场考官量规、证据记录和签名。',
    id: 'core.rubric',
    name: '现场量规',
    packageKind: 'built-in',
    sandbox: 'none',
    status: 'enabled',
    testSummary: { failed: 0, lastRunAt: createdAt, passed: 12 },
    version: '2.1.0',
  },
  {
    capabilities: {
      accessibility: true,
      authoring: true,
      automaticScoring: true,
      online: true,
      practical: false,
      print: false,
    },
    description: '多语言代码编辑、测试用例和隔离执行。',
    id: 'professional.programming',
    name: '程序设计沙箱',
    packageKind: 'school-developed',
    sampleItemId: 'item-programming@1',
    sandbox: 'isolated-service',
    status: 'testing',
    testSummary: { failed: 1, lastRunAt: createdAt, passed: 26 },
    version: '1.4.0',
  },
  {
    capabilities: {
      accessibility: false,
      authoring: true,
      automaticScoring: false,
      online: true,
      practical: true,
      print: false,
    },
    description: 'DICOM 序列查看、窗宽窗位和区域标注。',
    id: 'professional.medical-imaging',
    name: '医学影像标注',
    packageKind: 'vendor',
    sampleItemId: 'item-medical@1',
    sandbox: 'signed-iframe',
    status: 'enabled',
    testSummary: { failed: 0, lastRunAt: createdAt, passed: 17 },
    version: '3.0.2',
  },
  {
    capabilities: {
      accessibility: false,
      authoring: true,
      automaticScoring: true,
      online: true,
      practical: true,
      print: false,
    },
    description: 'CAD 模型查看、尺寸约束和作品提交。',
    id: 'professional.cad',
    name: '工程 CAD 作品',
    packageKind: 'vendor',
    sandbox: 'signed-iframe',
    status: 'draft',
    testSummary: { failed: 3, lastRunAt: createdAt, passed: 8 },
    version: '0.9.0',
  },
  {
    capabilities: {
      accessibility: true,
      authoring: true,
      automaticScoring: false,
      online: true,
      practical: true,
      print: false,
    },
    description: '录音、计时、考官量规和口语证据。',
    id: 'professional.oral',
    name: '语言口试',
    packageKind: 'school-developed',
    sandbox: 'signed-iframe',
    status: 'enabled',
    testSummary: { failed: 0, lastRunAt: createdAt, passed: 15 },
    version: '1.2.1',
  },
  {
    capabilities: {
      accessibility: true,
      authoring: true,
      automaticScoring: true,
      online: true,
      practical: true,
      print: true,
    },
    description: '由教师拖拽基础控件生成的受控交互运行时。',
    id: 'builder.no-code',
    name: '无代码组合交互',
    packageKind: 'built-in',
    sampleItemId: 'item-material-composite@1',
    sandbox: 'none',
    status: 'enabled',
    testSummary: { failed: 0, lastRunAt: createdAt, passed: 32 },
    version: '1.0.0',
  },
];

function paragraph(id: string, text: string) {
  return { data: { text }, id, type: 'paragraph' as const };
}

function makeItem(input: {
  applicableMajorIds: string[];
  classificationIds: string[];
  config: JsonObject;
  difficulty: 1 | 2 | 3 | 4 | 5;
  familyId: string;
  id: string;
  maxScore: number;
  pluginId: string;
  primaryCourseId: string;
  scoreMode?: 'automatic' | 'external' | 'human' | 'hybrid';
  status?: AssessmentItemRevision['status'];
  stem: string;
  tags: string[];
  templateRevisionId?: string;
  title: string;
}): AssessmentItemRevision {
  return {
    channelVariants: [
      { channel: 'online', mode: 'native' },
      {
        channel: 'print',
        mode: input.pluginId.startsWith('professional.')
          ? 'unsupported'
          : 'equivalent',
      },
      {
        channel: 'practical',
        mode:
          input.pluginId === 'core.rubric' ||
          input.pluginId === 'professional.medical-imaging'
            ? 'native'
            : 'equivalent',
      },
    ],
    checksum: `checksum-${input.id}`,
    classification: {
      cognitiveLevel: input.tags.includes('综合') ? 'analyze' : 'apply',
      freeTags: input.tags,
      taxonomyNodeIds: input.classificationIds,
    },
    createdAt,
    createdBy: 'teacher-demo',
    familyId: input.familyId,
    id: input.id,
    interaction: {
      config: input.config,
      kind: input.templateRevisionId ? 'template' : 'plugin',
      pluginId: input.pluginId,
      pluginVersion:
        pluginPackages.find((plugin) => plugin.id === input.pluginId)
          ?.version ?? '1.0.0',
      templateRevisionId: input.templateRevisionId,
    },
    language: 'zh-CN',
    maxScore: input.maxScore,
    metadata: {
      applicability: {
        curriculumPlanIds: ['plan-2025'],
        disciplineIds: ['discipline-engineering'],
        educationLevels: ['本科'],
        gradeBands: ['大一', '大二'],
        majorIds: input.applicableMajorIds,
        reusableCourseIds: [input.primaryCourseId],
      },
      confidentiality: 'internal',
      difficulty: input.difficulty,
      estimatedSeconds: input.maxScore * 50,
      ownership: {
        authorIds: ['teacher-demo'],
        maintainerTeam: '课程命题组',
        ownerOrgId: input.primaryCourseId.includes('diagnostics')
          ? 'college-medical'
          : 'college-engineering',
        primaryCourseId: input.primaryCourseId,
        visibility: 'school',
      },
      quality: {
        discrimination: input.status === 'published' ? 0.37 : undefined,
        exposureCount: input.status === 'published' ? 28 : 0,
        pValue: input.status === 'published' ? 0.64 : undefined,
        sampleSize: input.status === 'published' ? 186 : 0,
        usageCount: input.status === 'published' ? 4 : 0,
      },
      source: '校内原创',
    },
    revision: Number(input.id.split('@')[1] ?? 1),
    scoring: {
      config: {},
      mode: input.scoreMode ?? 'automatic',
      policyVersion: '1.0',
    },
    status: input.status ?? 'published',
    stem: {
      blocks: [paragraph(`block-${input.id}`, input.stem)],
      schemaVersion: '1.0',
    },
    title: input.title,
  };
}

const itemRevisions: AssessmentItemRevision[] = [
  makeItem({
    applicableMajorIds: [
      'major-computer',
      'major-electrical',
      'major-mechanical',
    ],
    classificationIds: ['node-integral', 'node-modeling', 'node-graduate-1'],
    config: {
      correct: ['B'],
      multiple: false,
      options: [
        { key: 'A', text: '1/2' },
        { key: 'B', text: '1' },
        { key: 'C', text: '2' },
        { key: 'D', text: '不存在' },
      ],
    },
    difficulty: 3,
    familyId: 'item-calculus-choice',
    id: 'item-calculus-choice@2',
    maxScore: 5,
    pluginId: 'core.choice',
    primaryCourseId: 'course-calculus',
    stem: '计算定积分 ∫₀¹ 2x dx，并选择正确结果。',
    tags: ['共享基础课', '定积分'],
    title: '定积分基础计算',
  }),
  makeItem({
    applicableMajorIds: [
      'major-computer',
      'major-electrical',
      'major-mechanical',
    ],
    classificationIds: ['node-integral', 'node-modeling'],
    config: { expected: 0.333, tolerance: 0.01, units: ['m³', 'cm³'] },
    difficulty: 4,
    familyId: 'item-integral-numeric',
    id: 'item-integral-numeric@1',
    maxScore: 10,
    pluginId: 'core.numeric',
    primaryCourseId: 'course-calculus',
    stem: '某旋转体由曲线 y=x² 在 [0,1] 上绕 x 轴旋转形成，请计算体积。',
    tags: ['共享基础课', '工程应用', '综合'],
    title: '旋转体体积计算',
  }),
  makeItem({
    applicableMajorIds: ['major-computer'],
    classificationIds: ['node-data-structure'],
    config: { language: 'typescript', tests: 8 },
    difficulty: 4,
    familyId: 'item-programming',
    id: 'item-programming@1',
    maxScore: 20,
    pluginId: 'professional.programming',
    primaryCourseId: 'course-programming',
    scoreMode: 'external',
    stem: '实现一个支持 O(1) 查询最小值的栈，并通过给定测试。',
    tags: ['程序设计', '沙箱', '综合'],
    title: '最小栈编程题',
  }),
  makeItem({
    applicableMajorIds: ['major-mechanical', 'major-electrical'],
    classificationIds: [
      'node-stress',
      'node-engineering-analysis',
      'node-scenario-engineering',
    ],
    config: { templateRevisionId: 'template-material@3' },
    difficulty: 4,
    familyId: 'item-material-composite',
    id: 'item-material-composite@1',
    maxScore: 15,
    pluginId: 'builder.no-code',
    primaryCourseId: 'course-mechanics',
    scoreMode: 'hybrid',
    stem: '已知杆件载荷与截面积，请计算正应力、判断强度并说明依据。',
    tags: ['工程场景', '复合交互', '综合'],
    templateRevisionId: 'template-material@3',
    title: '杆件强度综合分析',
  }),
  makeItem({
    applicableMajorIds: ['major-clinical'],
    classificationIds: [
      'node-imaging',
      'node-clinical-reasoning',
      'node-scenario-medical',
    ],
    config: { studyId: 'dicom-demo-001', tools: ['window', 'annotation'] },
    difficulty: 5,
    familyId: 'item-medical',
    id: 'item-medical@1',
    maxScore: 20,
    pluginId: 'professional.medical-imaging',
    primaryCourseId: 'course-diagnostics',
    scoreMode: 'human',
    stem: '观察胸部 CT 序列，标注异常区域并给出诊断依据。',
    tags: ['临床场景', '医学影像', '综合'],
    title: '胸部 CT 影像判读',
  }),
  makeItem({
    applicableMajorIds: ['major-clinical'],
    classificationIds: ['node-clinical-reasoning', 'node-scenario-medical'],
    config: { templateRevisionId: 'template-clinical@2' },
    difficulty: 4,
    familyId: 'item-clinical-station',
    id: 'item-clinical-station@1',
    maxScore: 20,
    pluginId: 'core.rubric',
    primaryCourseId: 'course-diagnostics',
    scoreMode: 'human',
    stem: '完成标准化病人问诊并形成初步诊断，考官依据量规记录证据。',
    tags: ['OSCE', '实践', '综合'],
    templateRevisionId: 'template-clinical@2',
    title: '标准化病人问诊考站',
  }),
  makeItem({
    applicableMajorIds: ['major-english'],
    classificationIds: [],
    config: { maxLength: 1200, minLength: 300 },
    difficulty: 3,
    familyId: 'item-essay',
    id: 'item-essay@1',
    maxScore: 15,
    pluginId: 'core.essay',
    primaryCourseId: 'course-academic-english',
    scoreMode: 'human',
    stem: '阅读材料后，从论点、证据与结构三个角度撰写英文评论。',
    tags: ['学术英语', '论述'],
    title: '学术评论写作',
  }),
  makeItem({
    applicableMajorIds: ['major-mechanical'],
    classificationIds: ['node-scenario-engineering'],
    config: { extensions: ['step', 'stp'], maxSizeMb: 50 },
    difficulty: 5,
    familyId: 'item-cad',
    id: 'item-cad@1',
    maxScore: 25,
    pluginId: 'professional.cad',
    primaryCourseId: 'course-mechanics',
    scoreMode: 'external',
    status: 'review',
    stem: '根据装配要求完成零件三维建模并提交 STEP 文件。',
    tags: ['CAD', '工程作品', '综合'],
    title: '轴承座三维建模',
  }),
  makeItem({
    applicableMajorIds: ['major-english'],
    classificationIds: [],
    config: { durationSeconds: 120, prompts: 2 },
    difficulty: 3,
    familyId: 'item-oral',
    id: 'item-oral@1',
    maxScore: 10,
    pluginId: 'professional.oral',
    primaryCourseId: 'course-academic-english',
    scoreMode: 'hybrid',
    stem: '围绕给定校园议题完成两分钟陈述，并回答考官追问。',
    tags: ['口试', '实践'],
    title: '英语主题陈述',
  }),
  makeItem({
    applicableMajorIds: ['major-computer'],
    classificationIds: ['node-data-structure'],
    config: { answers: ['栈', '队列'] },
    difficulty: 2,
    familyId: 'item-fill',
    id: 'item-fill@1',
    maxScore: 5,
    pluginId: 'core.fill',
    primaryCourseId: 'course-programming',
    stem: '后进先出的线性结构称为____，先进先出的线性结构称为____。',
    tags: ['基础概念'],
    title: '线性结构概念填空',
  }),
];

const blueprints: AssessmentBlueprint[] = [
  {
    applicableMajorIds: [
      'major-computer',
      'major-electrical',
      'major-mechanical',
    ],
    channels: ['online', 'print'],
    courseIds: ['course-calculus', 'course-mechanics'],
    createdAt,
    durationMinutes: 120,
    id: 'blueprint-engineering',
    name: '工程类基础能力综合考试蓝图',
    sections: [
      {
        id: 'section-foundation',
        name: '基础知识与计算',
        rules: [
          {
            applicabilityMajorIds: [],
            channels: ['online', 'print'],
            count: 2,
            difficultyRange: [2, 4],
            interactionIds: ['core.choice', 'core.numeric'],
            scorePerItem: 10,
            taxonomyNodeIds: ['node-calculus'],
          },
        ],
      },
      {
        id: 'section-application',
        name: '工程综合应用',
        rules: [
          {
            applicabilityMajorIds: ['major-electrical', 'major-mechanical'],
            channels: ['online', 'print'],
            count: 1,
            difficultyRange: [3, 5],
            interactionIds: ['builder.no-code'],
            scorePerItem: 20,
            taxonomyNodeIds: ['node-engineering-analysis'],
          },
        ],
      },
    ],
    status: 'published',
    totalScore: 40,
  },
  {
    applicableMajorIds: ['major-clinical'],
    channels: ['practical'],
    courseIds: ['course-diagnostics'],
    createdAt,
    durationMinutes: 30,
    id: 'blueprint-clinical',
    name: '临床诊断 OSCE 蓝图',
    sections: [
      {
        id: 'section-osce',
        name: '临床考站',
        rules: [
          {
            applicabilityMajorIds: ['major-clinical'],
            channels: ['practical'],
            count: 1,
            difficultyRange: [3, 5],
            interactionIds: ['core.rubric', 'professional.medical-imaging'],
            scorePerItem: 20,
            taxonomyNodeIds: ['node-clinical-reasoning'],
          },
        ],
      },
    ],
    status: 'published',
    totalScore: 20,
  },
];

function requireSeedItem(index: number) {
  const item = itemRevisions[index];
  if (!item) {
    throw new Error(`演示题目 ${index} 不存在`);
  }
  return item;
}

function createSeedForm(): TestFormRevision {
  const selected = [
    { item: requireSeedItem(0), score: 10 },
    { item: requireSeedItem(1), score: 10 },
    { item: requireSeedItem(3), score: 20 },
  ].map(({ item, score }) => ({
    itemRevision: structuredClone(item),
    score,
  }));
  return {
    blueprintId: 'blueprint-engineering',
    channels: ['online', 'print'],
    checksum: 'form-engineering-a-v2',
    compatibility: [],
    createdAt,
    createdBy: 'paper-team',
    durationMinutes: 120,
    id: 'form-engineering-a@2',
    name: '工程类基础能力综合考试 · A 卷',
    onlineProfile: {
      allowBacktrack: true,
      calculator: true,
      id: 'online-standard',
      name: '标准机考',
      navigation: 'one-per-page',
    },
    printProfile: {
      answerArea: 'separate-booklet',
      bindingEdgeMillimeters: 12,
      columns: 1,
      duplex: true,
      fontSizePoints: 11,
      id: 'print-a4-standard',
      name: 'A4 双面标准卷',
      pageSize: 'A4',
    },
    revision: 2,
    sections: [
      {
        id: 'section-foundation',
        items: selected.slice(0, 2),
        name: '基础知识与计算',
      },
      {
        id: 'section-application',
        items: selected.slice(2),
        name: '工程综合应用',
      },
    ],
    status: 'sealed',
    totalScore: selected.reduce((total, entry) => total + entry.score, 0),
    variant: 'A',
  };
}

function createClinicalForm(): TestFormRevision {
  const selected = [requireSeedItem(4), requireSeedItem(5)].map((item) => ({
    itemRevision: structuredClone(item),
    score: 20,
  }));
  return {
    blueprintId: 'blueprint-clinical',
    channels: ['practical'],
    checksum: 'form-clinical-osce-v1',
    compatibility: [],
    createdAt,
    createdBy: 'paper-team-medical',
    durationMinutes: 30,
    id: 'form-clinical-osce@1',
    name: '临床诊断 OSCE · 正式卷',
    onlineProfile: {
      allowBacktrack: false,
      calculator: false,
      id: 'online-osce',
      name: '考站顺序模式',
      navigation: 'linear',
    },
    printProfile: {
      answerArea: 'separate-booklet',
      bindingEdgeMillimeters: 12,
      columns: 1,
      duplex: false,
      fontSizePoints: 11,
      id: 'print-osce-rubric',
      name: '考官量规',
      pageSize: 'A4',
    },
    revision: 1,
    sections: [
      {
        id: 'section-osce',
        items: selected,
        name: '临床考站',
      },
    ],
    status: 'sealed',
    totalScore: 40,
    variant: '正式',
  };
}

export function createSeedState(): SchoolAssessmentState {
  const form = createSeedForm();
  const clinicalForm = createClinicalForm();
  return {
    activeItemId: itemRevisions[0]?.id ?? '',
    appeals: [
      {
        applicantId: 'student-20250018',
        attemptId: 'attempt-demo-submitted',
        createdAt,
        id: 'appeal-001',
        reason: '申请复核论述题评分依据。',
        status: 'pending',
      },
    ],
    attempts: [
      {
        candidateId: 'student-20250018',
        eventId: 'event-online',
        id: 'attempt-demo-submitted',
        lastSavedAt: createdAt,
        responseSequence: 3,
        responses: {
          'item-calculus-choice@2': {
            pluginId: 'core.choice',
            value: 'B',
          },
          'item-integral-numeric@1': {
            pluginId: 'core.numeric',
            value: { unit: 'm³', value: 0.33 },
          },
          'item-material-composite@1': {
            pluginId: 'builder.no-code',
            value: {
              'ctrl-judgement': '安全',
              'ctrl-reason': '计算应力低于许用应力。',
              'ctrl-stress': 248,
            },
          },
        },
        startedAt: createdAt,
        status: 'scoring',
        submittedAt: createdAt,
        testFormRevisionId: form.id,
      },
    ],
    auditRecords: [
      {
        action: 'paper.sealed',
        actorId: 'paper-approver',
        chainHash: 'audit-chain-001',
        id: 'audit-001',
        metadata: { checksum: form.checksum },
        occurredAt: createdAt,
        outcome: 'success',
        previousHash: 'GENESIS',
        resourceId: form.id,
        resourceType: 'test-form',
      },
    ],
    blueprints,
    connection: 'online',
    courses: [
      {
        applicableMajorIds: [
          'major-computer',
          'major-electrical',
          'major-mechanical',
        ],
        code: 'MATH1001',
        credit: 5,
        id: 'course-calculus',
        name: '高等数学',
        ownerOrgId: 'department-math',
        sharedAcrossMajors: true,
      },
      {
        applicableMajorIds: ['major-computer'],
        code: 'CS2001',
        credit: 4,
        id: 'course-programming',
        name: '程序设计与数据结构',
        ownerOrgId: 'college-engineering',
        sharedAcrossMajors: false,
      },
      {
        applicableMajorIds: ['major-mechanical', 'major-electrical'],
        code: 'ME2101',
        credit: 4,
        id: 'course-mechanics',
        name: '工程力学',
        ownerOrgId: 'college-engineering',
        sharedAcrossMajors: true,
      },
      {
        applicableMajorIds: ['major-clinical'],
        code: 'MED3102',
        credit: 3,
        id: 'course-diagnostics',
        name: '临床诊断学',
        ownerOrgId: 'college-medical',
        sharedAcrossMajors: false,
      },
      {
        applicableMajorIds: ['major-english'],
        code: 'ENG2103',
        credit: 3,
        id: 'course-academic-english',
        name: '学术英语',
        ownerOrgId: 'college-humanities',
        sharedAcrossMajors: false,
      },
    ],
    curriculumPlans: [
      {
        courseIds: ['course-calculus', 'course-programming'],
        id: 'plan-2025',
        majorId: 'major-computer',
        name: '计算机科学与技术 2025 培养方案',
        version: '2025',
      },
    ],
    disciplines: [
      {
        code: '08',
        id: 'discipline-engineering',
        level: 'category',
        name: '工学',
        parentId: null,
      },
      {
        code: '10',
        id: 'discipline-medical',
        level: 'category',
        name: '医学',
        parentId: null,
      },
      {
        code: '05',
        id: 'discipline-literature',
        level: 'category',
        name: '文学',
        parentId: null,
      },
    ],
    events: [
      {
        approvalActorIds: ['approver-a', 'approver-b'],
        assuranceLevel: 'standard',
        candidateIds: ['student-20250018', 'student-20250021'],
        createdAt,
        createdBy: 'exam-manager',
        deliveryMode: 'online',
        endAt: '2026-08-22T04:00:00.000Z',
        id: 'event-online',
        name: '2025-2026 学年工程基础综合考试',
        settings: {
          allowResume: true,
          extraTimePercent: 0,
          randomizeItems: true,
          requireFullscreen: true,
        },
        startAt: '2026-08-22T02:00:00.000Z',
        status: 'scoring',
        testFormRevisionId: form.id,
      },
      {
        approvalActorIds: ['approver-a'],
        assuranceLevel: 'standard',
        candidateIds: ['student-20250031'],
        createdAt,
        createdBy: 'exam-manager',
        deliveryMode: 'paper',
        endAt: '2026-08-28T04:00:00.000Z',
        id: 'event-paper',
        name: '工程基础补考试卷',
        settings: {
          allowResume: false,
          extraTimePercent: 0,
          randomizeItems: false,
          requireFullscreen: false,
        },
        startAt: '2026-08-28T02:00:00.000Z',
        status: 'ready',
        testFormRevisionId: form.id,
      },
      {
        approvalActorIds: ['approver-medical-a', 'approver-medical-b'],
        assuranceLevel: 'high-stakes',
        candidateIds: ['student-med-001'],
        createdAt,
        createdBy: 'exam-manager-medical',
        deliveryMode: 'practical',
        endAt: '2026-09-02T04:00:00.000Z',
        id: 'event-practical',
        name: '临床诊断 OSCE',
        settings: {
          allowResume: false,
          extraTimePercent: 0,
          randomizeItems: false,
          requireFullscreen: false,
        },
        startAt: '2026-09-02T01:00:00.000Z',
        status: 'scheduled',
        testFormRevisionId: clinicalForm.id,
      },
    ],
    forms: [form, clinicalForm],
    interactionTemplates,
    itemRevisions,
    majors: [
      {
        code: '080901',
        collegeId: 'college-engineering',
        degreeLevel: 'bachelor',
        disciplineId: 'discipline-engineering',
        id: 'major-computer',
        name: '计算机科学与技术',
      },
      {
        code: '080201',
        collegeId: 'college-engineering',
        degreeLevel: 'bachelor',
        disciplineId: 'discipline-engineering',
        id: 'major-mechanical',
        name: '机械工程',
      },
      {
        code: '080601',
        collegeId: 'college-engineering',
        degreeLevel: 'bachelor',
        disciplineId: 'discipline-engineering',
        id: 'major-electrical',
        name: '电气工程及其自动化',
      },
      {
        code: '100201K',
        collegeId: 'college-medical',
        degreeLevel: 'bachelor',
        disciplineId: 'discipline-medical',
        id: 'major-clinical',
        name: '临床医学',
      },
      {
        code: '050201',
        collegeId: 'college-humanities',
        degreeLevel: 'bachelor',
        disciplineId: 'discipline-literature',
        id: 'major-english',
        name: '英语',
      },
    ],
    organizationNodes: [
      {
        code: 'SCHOOL',
        id: 'school-demo',
        name: '知测大学',
        parentId: null,
        type: 'school',
      },
      {
        code: 'ENG',
        id: 'college-engineering',
        name: '工程学院',
        parentId: 'school-demo',
        type: 'college',
      },
      {
        code: 'MED',
        id: 'college-medical',
        name: '医学院',
        parentId: 'school-demo',
        type: 'college',
      },
      {
        code: 'HUM',
        id: 'college-humanities',
        name: '人文学院',
        parentId: 'school-demo',
        type: 'college',
      },
      {
        code: 'MATH',
        id: 'department-math',
        name: '公共数学教学部',
        parentId: 'school-demo',
        type: 'teaching-unit',
      },
    ],
    paperBatches: [
      {
        bookletCount: 1,
        collectedCount: 0,
        eventId: 'event-paper',
        id: 'batch-paper-001',
        printedCount: 1,
        status: 'ready',
      },
    ],
    pluginPackages,
    practicalStations: [
      {
        evidenceTypes: ['rubric', 'audio', 'video'],
        examinerIds: ['examiner-med-001', 'examiner-med-002'],
        id: 'station-osce-01',
        name: 'OSCE 诊断问诊站',
        status: 'ready',
      },
    ],
    responseEvents: [],
    scanJobs: [
      {
        batchId: 'batch-paper-001',
        errorCount: 2,
        id: 'scan-job-001',
        pageCount: 36,
        reviewedCount: 21,
        status: 'reviewing',
      },
    ],
    school: {
      academicYear: '2025-2026',
      code: 'ZHICE',
      id: 'school-demo',
      name: '知测大学',
      semester: '第二学期',
    },
    scoreRecords: [
      {
        algorithmVersion: 'core.choice@2.1.0',
        attemptId: 'attempt-demo-submitted',
        awardedScore: 10,
        evidence: ['答案 B 与标准答案一致'],
        id: 'score-choice',
        itemRevisionId: 'item-calculus-choice@2',
        maxScore: 10,
        method: 'automatic',
        status: 'automatic',
      },
      {
        algorithmVersion: 'core.numeric@2.2.0',
        attemptId: 'attempt-demo-submitted',
        awardedScore: 9,
        evidence: ['数值在容差范围内', '单位正确'],
        id: 'score-numeric',
        itemRevisionId: 'item-integral-numeric@1',
        maxScore: 10,
        method: 'automatic',
        status: 'automatic',
      },
      {
        algorithmVersion: 'template-material@3',
        attemptId: 'attempt-demo-submitted',
        awardedScore: 8,
        evidence: ['自动部分 7 分', '分析说明待人工评分'],
        firstScore: 16,
        id: 'score-material',
        itemRevisionId: 'item-material-composite@1',
        maxScore: 20,
        method: 'human',
        status: 'first-marked',
      },
    ],
    submissions: [],
    taxonomyEdges: [
      {
        fromId: 'node-modeling',
        id: 'edge-modeling-graduate',
        relation: 'supports',
        schemeId: 'scheme-ability',
        toId: 'node-graduate-1',
      },
    ],
    taxonomyNodes,
    taxonomySchemes,
  };
}
